version: '3.1'

services:
  mattermost:
    build: ./mattermost
    restart: always
    volumes:
      - ./mattermost/data/mysql:/var/lib/mysql
    ports:
      - 8065:8065
      - 9200:9200
    environment:
      - MYSQL_ROOT_PASSWORD=mostest
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mostest

  say-hello:
    build: ./java
    restart: always
    command: java fr.upem.hello.HelloWorld

  portainer:
    build: ./portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    ports:
      - 9000:9000
    command: --admin-password $$2y$$05$$gSS80HP4M2EQ3lhw9O3.ruqn7NMzkFltUy9U1me4cfBJk4GCc23lm
    depends_on:
      - mattermost
      - say-hello
